# 
# If you change this file - restart the jekyll server
# 

# Site settings
url: "https://fiddlydigital.com" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog

# Site MetaData
title: FiddlyDigital
description: One man's journey of discovery in the Digital Realm
  
# Contact Details
email: fiddlydigital@gmail.com
disqus_shortname : fiddlydigital

# Build settings
markdown: kramdown
exclude: [bower.json, package.json, .bowerrc, .gitignore]
